# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMMmR0YY8MfsymLTvpPe2BvfDmhISyF7
"""



import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

# Title
st.title("AI Customer Churn Prediction & Analytics Dashboard")

# Load dataset
df = pd.read_csv("/content/sample_customer_data.csv")

st.subheader("Dataset Preview")
st.write(df.head())

# -----------------------------
# EDA SECTION
# -----------------------------

st.subheader("Customer Age Distribution")

fig1, ax1 = plt.subplots()
sns.histplot(df['Age'], kde=True, ax=ax1)
st.pyplot(fig1)

st.subheader("Gender Distribution")

fig2, ax2 = plt.subplots()
sns.countplot(x='Gender', data=df, ax=ax2)
st.pyplot(fig2)

st.subheader("Income vs Spending Score")

fig3, ax3 = plt.subplots()
sns.scatterplot(x='AnnualIncome', y='SpendingScore', data=df, ax=ax3)
st.pyplot(fig3)

# -----------------------------
# MODEL TRAINING
# -----------------------------

df_model = df.copy()

df_model['Gender'] = df_model['Gender'].map({'Male':0,'Female':1})

X = df_model[['Age','Gender','AnnualIncome','SpendingScore']]
y = df_model['SpendingScore'] > 50   # simple churn/purchase logic

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model = RandomForestClassifier()
model.fit(X_train,y_train)

# -----------------------------
# PREDICTION SECTION
# -----------------------------

st.sidebar.header("Customer Prediction")

age = st.sidebar.slider("Age",18,70,30)
gender = st.sidebar.selectbox("Gender",["Male","Female"])
income = st.sidebar.slider("Annual Income",10000,150000,50000)
score = st.sidebar.slider("Spending Score",1,100,50)

gender_val = 0 if gender=="Male" else 1

prediction = model.predict([[age,gender_val,income,score]])

if prediction[0]:
    st.sidebar.success("High Purchase Probability")
else:
    st.sidebar.warning("Low Purchase Probability")

# -----------------------------
# CUSTOMER SEGMENTATION
# -----------------------------

st.subheader("Customer Segmentation")

kmeans = KMeans(n_clusters=3)
df['segment'] = kmeans.fit_predict(df[['AnnualIncome','SpendingScore']])

fig4, ax4 = plt.subplots()
sns.scatterplot(
    x=df['AnnualIncome'],
    y=df['SpendingScore'],
    hue=df['segment'],
    palette="Set2",
    ax=ax4
)

st.pyplot(fig4)

# -----------------------------
# Feature Importance
# -----------------------------

st.subheader("Feature Importance")

importance = model.feature_importances_

features = pd.DataFrame({
    "Feature":X.columns,
    "Importance":importance
})

fig5, ax5 = plt.subplots()
sns.barplot(x="Importance",y="Feature",data=features,ax=ax5)

st.pyplot(fig5)

