# -*- coding: utf-8 -*-
"""notebooks/customer_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zS8g7OdzJt_mhVo5snDIsAbEwCOTcT2H
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/sample_customer_data.csv")

# Basic info
print(df.info())

# Distribution of age
sns.histplot(df['Age'], kde=True)
plt.title("Age Distribution")
plt.show()

# Income vs purchase score
sns.scatterplot(x='AnnualIncome', y='SpendingScore', data=df)
plt.title("Income vs Purchase Score")
plt.show()

# Correlation heatmap
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True)
plt.title("Feature Correlation")
plt.show()

gender_distribution = df['Gender'].value_counts()
print("Gender Distribution:\n", gender_distribution)

plt.figure(figsize=(6, 4))
sns.barplot(x=gender_distribution.index, y=gender_distribution.values)
plt.title("Distribution of Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Assuming 'df' is your DataFrame from the previous steps
# Drop CustomerID as it's an identifier and not a feature
df_model = df.drop('CustomerID', axis=1)

# Handle categorical features: One-hot encode 'Gender'
df_model = pd.get_dummies(df_model, columns=['Gender'], drop_first=True) # drop_first avoids multicollinearity

# Define features (X) and target (y)
X = df_model.drop('PurchaseLikelihood', axis=1)
y = df_model['PurchaseLikelihood']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""Now, let's train a Random Forest Classifier and evaluate its performance."""

# Initialize the Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42) # n_estimators is the number of trees in the forest

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
print("Model Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)
df['segment'] = kmeans.fit_predict(df[['AnnualIncome','SpendingScore']])

sns.scatterplot(
    x=df['AnnualIncome'],
    y=df['SpendingScore'],
    hue=df['segment'],
    palette="Set2"
)
plt.title("Customer Segmentation")
plt.show()

